---
env:
  browser: true
  node: true
  es6: true

extends:
  - eslint:recommended

globals:
  nw: readonly

parserOptions:
  ecmaVersion: 9
  sourceType: module

rules:
  eol-last:
    - warn
    - always
  indent:
    - warn
    - 2
    - SwitchCase: 1
  no-unused-vars:
    - warn
    - argsIgnorePattern: "^_"
  object-shorthand:
    - warn
    - methods
  quotes:
    - error
    - double
    - allowTemplateLiterals: true
  semi:
    - warn
    - never
