---
env:
  browser: true
  node: true

extends:
  - eslint:recommended

globals:
  nw: readonly

parserOptions:
  ecmaVersion: 9
  sourceType: module

rules:
  eol-last:
    - warn
    - always
  no-unused-vars:
    - warn
    - argsIgnorePattern: "^_"
  quotes:
    - error
    - double
    - allowTemplateLiterals: true
  semi:
    - warn
    - never
