name: Deploys

on:
  release:
    types: [created]

jobs:
  macos:
    name: Deploy for ${{ matrix.phoenix_task }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45

    strategy:
      fail-fast: false

      # Idea from https://github.community/t5/GitHub-Actions/Create-matrix-with-multiple-OS-and-env-for-each-one/m-p/38574#M3418
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

        include:
        - os: macos-latest
          package_suffix: macos
          phoenix_task: mac-x64

        - os: ubuntu-latest
          package_suffix: linux-amd64
          phoenix_task: linux-x86,linux-x64

        - os: windows-latest
          package_suffix: windows
          phoenix_task: win-x86,win-x64

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - uses: actions/checkout@v2

      - name: Obtain tag name
        id: tag_name
        shell: bash
        # https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/m-p/32167#M1027
        # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        run: |
          echo "VERSION=${GITHUB_REF/refs\/tags\//}" | tee -a $GITHUB_ENV

      - name: Prepare artifacts directory
        shell: bash
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/artifacts"
          echo "ARTIFACTS=${GITHUB_WORKSPACE}/artifacts" | tee -a $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build
        shell: bash
        run: node_modules/.bin/build --tasks ${TASKS} --mirror "${MIRROR}" .
        env:
          MIRROR: https://dl.nwjs.io
          TASKS: ${{ matrix.phoenix_task }}

      - name: Package for Linux (generic)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          cd dist &&
          tar czf "${PKG_PREFIX}-32bit.tar.gz" fotorelacjonusz-*-x86 &&
          tar czf "${PKG_PREFIX}-64bit.tar.gz" fotorelacjonusz-*-x64 &&
          mv *.tar.gz "${ARTIFACTS}"
        env:
          PKG_PREFIX: Fotorelacjonusz-${{ env.VERSION }}-linux

      - name: Package for Linux (Debian)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          cd dist &&
          ../deploy_utils/debian/package.sh fotorelacjonusz-*-x86 i386 &&
          ../deploy_utils/debian/package.sh fotorelacjonusz-*-x64 amd64 &&
          mv *_i386.deb "${PKG_PREFIX}-32bit.deb" &&
          mv *_amd64.deb "${PKG_PREFIX}-64bit.deb" &&
          cp *.deb "${ARTIFACTS}"
        env:
          PKG_PREFIX: Fotorelacjonusz-${{ env.VERSION }}-linux

      - name: Package for Linux (RPM)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get install -y alien &&
          cd dist &&
          fakeroot alien --to-rpm --keep-version *-32bit.deb &&
          mv *.rpm "${ARTIFACTS}/${PKG_PREFIX}-32bit.rpm" &&
          fakeroot alien --to-rpm --keep-version *-64bit.deb &&
          mv *.rpm "${ARTIFACTS}/${PKG_PREFIX}-64bit.rpm"
        env:
          PKG_PREFIX: Fotorelacjonusz-${{ env.VERSION }}-linux

      - name: Package for macOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          cd dist/fotorelacjonusz-* &&
          tar czf "${PKG_PREFIX}.tar.gz" Fotorelacjonusz.app &&
          mv *.tar.gz "${ARTIFACTS}"
        env:
          PKG_PREFIX: Fotorelacjonusz-${{ env.VERSION }}-macos

      - name: Package for Windows (zipped)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          cd dist &&
          7z a -tzip "${PKG_PREFIX}-32bit.zip" fotorelacjonusz-*-x86 &&
          7z a -tzip "${PKG_PREFIX}-64bit.zip" fotorelacjonusz-*-x64 &&
          mv *.zip "${ARTIFACTS}"
        env:
          PKG_PREFIX: Fotorelacjonusz-${{ env.VERSION }}-windows

      - name: Package for Windows (installer)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          cd dist &&
          cp ../deploy_utils/installer.iss . &&
          cp -r fotorelacjonusz-*-win-x64 InstallerInput &&
          iscc "//DAPP_ARCH=x64" "//DAPP_VERSION=${VERSION#v}" "installer.iss" &&
          rm -r InstallerInput &&
          mv mysetup.exe "${PKG_PREFIX}-64bit.exe" &&
          cp -r fotorelacjonusz-*-win-x86 InstallerInput &&
          iscc "//DAPP_ARCH="    "//DAPP_VERSION=${VERSION#v}" "installer.iss" &&
          rm -r InstallerInput &&
          mv mysetup.exe "${PKG_PREFIX}-32bit.exe" &&
          mv *.exe "${ARTIFACTS}"
        env:
          PKG_PREFIX: Fotorelacjonusz-${{ env.VERSION }}-windows-installer

      - name: List artifacts
        shell: bash
        run: ls -l "${ARTIFACTS}"

      - name: Upload assets
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.ARTIFACTS }}/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
